<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.evantagesoft.usihub</groupId>
    <artifactId>USIHubMiddleware</artifactId>
    <version>1.0.0-SNAPSHOT</version>
  </parent>
  <groupId>com.evantagesoft.usihub</groupId>
  <artifactId>USIHubMiddlewareCompositeExporter</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <packaging>carbon/application</packaging>
  <name>USIHubMiddlewareCompositeExporter</name>
  <description>USIHubMiddlewareCompositeExporter</description>
  <properties>
    <com.evantagesoft.connector.thunes.endpoint_._CreateQuotationsEndpoint>capp/EnterpriseServiceBus</com.evantagesoft.connector.thunes.endpoint_._CreateQuotationsEndpoint>
    <com.evantagesoft.usihub.metadata_._USIHub_swagger>capp/EnterpriseServiceBus</com.evantagesoft.usihub.metadata_._USIHub_swagger>
    <com.evantagesoft.connector.thunes.sequence_._TransactionIteratorSequence>capp/EnterpriseServiceBus</com.evantagesoft.connector.thunes.sequence_._TransactionIteratorSequence>
    <com.evantagesoft.connector.thunes.api_._ThunesConnector>capp/EnterpriseServiceBus</com.evantagesoft.connector.thunes.api_._ThunesConnector>
    <com.evantagesoft.connector.thunes.sequence_._UpdateConfirmStatusSequence>capp/EnterpriseServiceBus</com.evantagesoft.connector.thunes.sequence_._UpdateConfirmStatusSequence>
    <artifact.types>jaggery/app=zip,synapse/priority-executor=xml,synapse/inbound-endpoint=xml,service/rule=aar,synapse/message-store=xml,event/stream=json,service/meta=xml,datasource/datasource=xml,synapse/proxy-service=xml,bpel/workflow=zip,synapse/sequence=xml,synapse/endpointTemplate=xml,carbon/application=car,wso2/gadget=dar,synapse/api=xml,synapse/event-source=xml,synapse/message-processors=xml,event/receiver=xml,lib/dataservice/validator=jar,synapse/template=xml,synapse/endpoint=xml,lib/carbon/ui=jar,lib/synapse/mediator=jar,synapse/metadata=yaml,event/publisher=xml,synapse/local-entry=xml,synapse/task=xml,webapp/jaxws=war,registry/resource=zip,synapse/configuration=xml,service/axis2=aar,synapse/lib=zip,synapse/sequenceTemplate=xml,event/execution-plan=siddhiql,service/dataservice=dbs,web/application=war,lib/library/bundle=jar</artifact.types>
    <com.evantagesoft.connector.thunes.sequence_._PayerDetailsIterator>capp/EnterpriseServiceBus</com.evantagesoft.connector.thunes.sequence_._PayerDetailsIterator>
    <com.example.sequence_._GetTransactionStatusDlocalSequence>capp/EnterpriseServiceBus</com.example.sequence_._GetTransactionStatusDlocalSequence>
    <com.evantagesoft.connector.thunes.sequence_._FetchPayersSequence>capp/EnterpriseServiceBus</com.evantagesoft.connector.thunes.sequence_._FetchPayersSequence>
    <com.evantagesoft.usihub.datasource_._datasource>capp/DataServicesServer</com.evantagesoft.usihub.datasource_._datasource>
    <com.evantagesoft.usihub.datasource_._USIHubDatasource>capp/DataServicesServer</com.evantagesoft.usihub.datasource_._USIHubDatasource>
    <com.evantagesoft.connector.thunes.endpoint_._GetTransactionEndpoint>capp/EnterpriseServiceBus</com.evantagesoft.connector.thunes.endpoint_._GetTransactionEndpoint>
    <com.evantagesoft.usihub.api_._USIHub>capp/EnterpriseServiceBus</com.evantagesoft.usihub.api_._USIHub>
    <com.evantagesoft.usihub.sequence_._BusinessRuleSequence>capp/EnterpriseServiceBus</com.evantagesoft.usihub.sequence_._BusinessRuleSequence>
    <com.example.endpoint_._SubmitPayoutEndpoint>capp/EnterpriseServiceBus</com.example.endpoint_._SubmitPayoutEndpoint>
    <com.evantagesoft.connector.thunes.sequence_._StorePayerDetails>capp/EnterpriseServiceBus</com.evantagesoft.connector.thunes.sequence_._StorePayerDetails>
    <com.example.sequence_._CheckPayoutResponseSequence>capp/EnterpriseServiceBus</com.example.sequence_._CheckPayoutResponseSequence>
    <com.example.sequence_._DlocalDataMappingSequence>capp/EnterpriseServiceBus</com.example.sequence_._DlocalDataMappingSequence>
    <com.evantagesoft.connector.thunes.endpoint_._GetPayerDetails>capp/EnterpriseServiceBus</com.evantagesoft.connector.thunes.endpoint_._GetPayerDetails>
    <com.evantagesoft.connector.thunes.sequence_._UpdateStatusSequence>capp/EnterpriseServiceBus</com.evantagesoft.connector.thunes.sequence_._UpdateStatusSequence>
    <com.evantagesoft.connector.thunes.metadata_._ThunesConnector_metadata>capp/EnterpriseServiceBus</com.evantagesoft.connector.thunes.metadata_._ThunesConnector_metadata>
    <com.evantagesoft.connector.thunes.metadata_._ThunesConnector_swagger>capp/EnterpriseServiceBus</com.evantagesoft.connector.thunes.metadata_._ThunesConnector_swagger>
    <com.evantagesoft.connector.thunes.sequence_._CreateTransactionSequence>capp/EnterpriseServiceBus</com.evantagesoft.connector.thunes.sequence_._CreateTransactionSequence>
    <com.evantagesoft.connector.thunes.dataservice_._GetISOCountryCodes>capp/DataServicesServer</com.evantagesoft.connector.thunes.dataservice_._GetISOCountryCodes>
    <com.example.endpoint_._CheckPayoutEndpoint>capp/EnterpriseServiceBus</com.example.endpoint_._CheckPayoutEndpoint>
    <com.example.sequence_._SubmitPayoutSequence>capp/EnterpriseServiceBus</com.example.sequence_._SubmitPayoutSequence>
    <com.evantagesoft.connector.thunes.sequence_._ConfirmTransactionSequence>capp/EnterpriseServiceBus</com.evantagesoft.connector.thunes.sequence_._ConfirmTransactionSequence>
    <com.evantagesoft.connector.thunes.sequence_._CountryCodeIterator>capp/EnterpriseServiceBus</com.evantagesoft.connector.thunes.sequence_._CountryCodeIterator>
    <com.example.sequence_._SubmitPayoutResponseSequence>capp/EnterpriseServiceBus</com.example.sequence_._SubmitPayoutResponseSequence>
    <com.evantagesoft.usihub.sequence_._ProcessResponse>capp/EnterpriseServiceBus</com.evantagesoft.usihub.sequence_._ProcessResponse>
    <com.evantagesoft.connector.thunes.sequence_._GetTransactionStatusSequence>capp/EnterpriseServiceBus</com.evantagesoft.connector.thunes.sequence_._GetTransactionStatusSequence>
    <com.evantagesoft.connector.thunes.endpoint_._GetCountryCodesEndpoint>capp/EnterpriseServiceBus</com.evantagesoft.connector.thunes.endpoint_._GetCountryCodesEndpoint>
    <com.evantagesoft.connector.thunes.sequence_._GetTransactionsSequence>capp/EnterpriseServiceBus</com.evantagesoft.connector.thunes.sequence_._GetTransactionsSequence>
    <com.evantagesoft.connector.thunes.sequence_._TransactionStatusIteratorSequence>capp/EnterpriseServiceBus</com.evantagesoft.connector.thunes.sequence_._TransactionStatusIteratorSequence>
    <com.example.api_._DlocalConnector>capp/EnterpriseServiceBus</com.example.api_._DlocalConnector>
    <com.evantagesoft.connector.thunes.endpoint_._ConfirmTransactionEndpoint>capp/EnterpriseServiceBus</com.evantagesoft.connector.thunes.endpoint_._ConfirmTransactionEndpoint>
    <com.evantagesoft.connector.thunes.sequence_._UpdateBankTransactionSequence>capp/EnterpriseServiceBus</com.evantagesoft.connector.thunes.sequence_._UpdateBankTransactionSequence>
    <com.evantagesoft.connector.thunes.message-store_._TransactionDetailStore>capp/EnterpriseServiceBus</com.evantagesoft.connector.thunes.message-store_._TransactionDetailStore>
    <com.evantagesoft.connector.thunes.sequence_._GetPayerDetailSequence>capp/EnterpriseServiceBus</com.evantagesoft.connector.thunes.sequence_._GetPayerDetailSequence>
    <com.example.sequence_._CheckPayoutStatusSequence>capp/EnterpriseServiceBus</com.example.sequence_._CheckPayoutStatusSequence>
    <com.example.datasource_._Dlocaldatasource>capp/DataServicesServer</com.example.datasource_._Dlocaldatasource>
    <com.evantagesoft.connector.thunes.datasource_._ThunesDatasource>capp/DataServicesServer</com.evantagesoft.connector.thunes.datasource_._ThunesDatasource>
    <com.evantagesoft.usihub.metadata_._USIHub_metadata>capp/EnterpriseServiceBus</com.evantagesoft.usihub.metadata_._USIHub_metadata>
    <com.evantagesoft.connector.thunes.sequence_._VaidateMessage>capp/EnterpriseServiceBus</com.evantagesoft.connector.thunes.sequence_._VaidateMessage>
    <com.example.sequence_._StatusParmDlocalSequence>capp/EnterpriseServiceBus</com.example.sequence_._StatusParmDlocalSequence>
    <com.evantagesoft.connector.thunes.endpoint_._CreateTransactionEndpoint>capp/EnterpriseServiceBus</com.evantagesoft.connector.thunes.endpoint_._CreateTransactionEndpoint>
    <com.evantagesoft.connector.thunes.sequence_._CreateQuotationsSequence>capp/EnterpriseServiceBus</com.evantagesoft.connector.thunes.sequence_._CreateQuotationsSequence>
  </properties>
  <dependencies>
    <dependency>
      <groupId>com.example.sequence</groupId>
      <artifactId>DlocalDataMappingSequence</artifactId>
      <version>1.0.0</version>
      <type>xml</type>
    </dependency>
    <dependency>
      <groupId>com.evantagesoft.connector.thunes.metadata</groupId>
      <artifactId>ThunesConnector_metadata</artifactId>
      <version>1.0.0</version>
      <type>yaml</type>
    </dependency>
    <dependency>
      <groupId>com.evantagesoft.usihub.datasource</groupId>
      <artifactId>datasource</artifactId>
      <version>5.2.42</version>
      <type>xml</type>
    </dependency>
    <dependency>
      <groupId>com.example.sequence</groupId>
      <artifactId>CheckPayoutStatusSequence</artifactId>
      <version>1.0.0</version>
      <type>xml</type>
    </dependency>
    <dependency>
      <groupId>com.example.endpoint</groupId>
      <artifactId>SubmitPayoutEndpoint</artifactId>
      <version>1.0.0</version>
      <type>xml</type>
    </dependency>
    <dependency>
      <groupId>com.evantagesoft.usihub.sequence</groupId>
      <artifactId>BusinessRuleSequence</artifactId>
      <version>1.0.0</version>
      <type>xml</type>
    </dependency>
    <dependency>
      <groupId>com.evantagesoft.usihub.metadata</groupId>
      <artifactId>USIHub_metadata</artifactId>
      <version>1.0.0</version>
      <type>yaml</type>
    </dependency>
    <dependency>
      <groupId>com.example.datasource</groupId>
      <artifactId>Dlocaldatasource</artifactId>
      <version>1.0.0</version>
      <type>xml</type>
    </dependency>
    <dependency>
      <groupId>com.example.sequence</groupId>
      <artifactId>GetTransactionStatusDlocalSequence</artifactId>
      <version>1.0.0</version>
      <type>xml</type>
    </dependency>
    <dependency>
      <groupId>com.example.sequence</groupId>
      <artifactId>CheckPayoutResponseSequence</artifactId>
      <version>1.0.0</version>
      <type>xml</type>
    </dependency>
    <dependency>
      <groupId>com.evantagesoft.usihub.metadata</groupId>
      <artifactId>USIHub_swagger</artifactId>
      <version>1.0.0</version>
      <type>yaml</type>
    </dependency>
    <dependency>
      <groupId>com.example.api</groupId>
      <artifactId>DlocalConnector</artifactId>
      <version>1.0.0</version>
      <type>xml</type>
    </dependency>
    <dependency>
      <groupId>com.example.endpoint</groupId>
      <artifactId>CheckPayoutEndpoint</artifactId>
      <version>1.0.0</version>
      <type>xml</type>
    </dependency>
    <dependency>
      <groupId>com.evantagesoft.usihub.datasource</groupId>
      <artifactId>USIHubDatasource</artifactId>
      <version>5.2.42</version>
      <type>xml</type>
    </dependency>
    <dependency>
      <groupId>com.evantagesoft.usihub.sequence</groupId>
      <artifactId>ProcessResponse</artifactId>
      <version>1.0.0</version>
      <type>xml</type>
    </dependency>
    <dependency>
      <groupId>com.evantagesoft.usihub.api</groupId>
      <artifactId>USIHub</artifactId>
      <version>1.0.0</version>
      <type>xml</type>
    </dependency>
    <dependency>
      <groupId>com.example.sequence</groupId>
      <artifactId>SubmitPayoutSequence</artifactId>
      <version>1.0.0</version>
      <type>xml</type>
    </dependency>
    <dependency>
      <groupId>com.evantagesoft.connector.thunes.metadata</groupId>
      <artifactId>ThunesConnector_swagger</artifactId>
      <version>1.0.0</version>
      <type>yaml</type>
    </dependency>
    <dependency>
      <groupId>com.example.sequence</groupId>
      <artifactId>StatusParmDlocalSequence</artifactId>
      <version>1.0.0</version>
      <type>xml</type>
    </dependency>
    <dependency>
      <groupId>com.example.sequence</groupId>
      <artifactId>SubmitPayoutResponseSequence</artifactId>
      <version>1.0.0</version>
      <type>xml</type>
    </dependency>
  </dependencies>
  <repositories>
    <repository>
      <releases>
        <enabled>true</enabled>
        <updatePolicy>daily</updatePolicy>
        <checksumPolicy>ignore</checksumPolicy>
      </releases>
      <id>wso2-nexus</id>
      <url>https://maven.wso2.org/nexus/content/groups/wso2-public/</url>
    </repository>
    <repository>
      <id>wso2-maven2-repository-1</id>
      <url>https://maven.wso2.org/nexus/content/groups/wso2-public/</url>
    </repository>
    <repository>
      <id>wso2-nexus-repository-1</id>
      <url>https://maven.wso2.org/nexus/content/groups/wso2-public/</url>
    </repository>
  </repositories>
  <pluginRepositories>
    <pluginRepository>
      <releases>
        <enabled>true</enabled>
        <updatePolicy>daily</updatePolicy>
        <checksumPolicy>ignore</checksumPolicy>
      </releases>
      <id>wso2-nexus</id>
      <url>https://maven.wso2.org/nexus/content/groups/wso2-public/</url>
    </pluginRepository>
    <pluginRepository>
      <id>wso2-maven2-repository-1</id>
      <url>https://maven.wso2.org/nexus/content/groups/wso2-public/</url>
    </pluginRepository>
    <pluginRepository>
      <id>wso2-nexus-repository-1</id>
      <url>https://maven.wso2.org/nexus/content/groups/wso2-public/</url>
    </pluginRepository>
  </pluginRepositories>
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-eclipse-plugin</artifactId>
        <version>2.9</version>
        <configuration>
          <buildcommands />
          <projectnatures>
            <projectnature>org.wso2.developerstudio.eclipse.distribution.project.nature</projectnature>
          </projectnatures>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.wso2.maven</groupId>
        <artifactId>maven-car-plugin</artifactId>
        <version>5.2.42</version>
        <extensions>true</extensions>
        <executions>
          <execution>
            <id>car</id>
            <phase>package</phase>
            <goals>
              <goal>car</goal>
            </goals>
          </execution>
        </executions>
        <dependencies>
          <dependency>
            <groupId>com.sun.activation</groupId>
            <artifactId>javax.activation</artifactId>
            <version>1.2.0</version>
          </dependency>
        </dependencies>
        <configuration />
      </plugin>
      <plugin>
        <groupId>org.wso2.maven</groupId>
        <artifactId>maven-car-deploy-plugin</artifactId>
        <version>5.2.42</version>
        <extensions>true</extensions>
        <dependencies>
          <dependency>
            <groupId>com.sun.activation</groupId>
            <artifactId>javax.activation</artifactId>
            <version>1.2.0</version>
          </dependency>
        </dependencies>
        <configuration>
          <carbonServers>
            <CarbonServer>
              <trustStorePath>${basedir}/src/main/resources/security/wso2carbon.jks</trustStorePath>
              <trustStorePassword>wso2carbon</trustStorePassword>
              <trustStoreType>JKS</trustStoreType>
              <serverUrl>https://localhost:9443</serverUrl>
              <userName>admin</userName>
              <password>admin</password>
              <operation>deploy</operation>
            </CarbonServer>
          </carbonServers>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
